FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app


COPY ./LackBot.Discord/*.csproj ./LackBot.Discord/
COPY ./LackBot.Common/*.csproj ./LackBot.Common/
RUN dotnet restore ./LackBot.Discord/LackBot.Discord.csproj


COPY ./LackBot.Discord/ ./LackBot.Discord/
COPY ./LackBot.Common/ ./LackBot.Common/
RUN dotnet publish ./LackBot.Discord/LackBot.Discord.csproj -c Release -o out


FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
COPY *.json ./
ENTRYPOINT ["dotnet", "LackBot.Discord.dll"]
