version: '3.7'
services: 
    lackbot_api:
        build:
            context: .
            dockerfile: Dockerfile_API
        ports:
            - '5000:80'
            - '5001:443'
        networks:
            - api
            - db
        environment:
            - DB_CREDENTIALS=db_credentials.json
        restart: unless-stopped
    lackbot_discord:
        build:
            context: .
            dockerfile: Dockerfile_Bot
        networks:
            - api
        environment:
            - BOT_CONFIG=bot_config.json
        restart: unless-stopped
    lackbot_frontend:
        build: frontend
        ports:
            - '4200:80'
        restart: unless-stopped
networks:
    api:
        name: api
        driver: bridge
    db:
        name: db
        external: true
