FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app


COPY ./LackBot.API/*.csproj ./LackBot.API/
COPY ./LackBot.Common/*.csproj ./LackBot.Common/
RUN dotnet restore ./LackBot.API/LackBot.API.csproj


COPY ./LackBot.API/ ./LackBot.API/
COPY ./LackBot.Common/ ./LackBot.Common/
RUN dotnet publish ./LackBot.API/LackBot.API.csproj -c Release -o out


FROM mcr.microsoft.com/dotnet/aspnet:5.0

# Change timezone to local time
ENV TZ=America/New_York
run ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
COPY --from=build-env /app/out .
COPY *.json ./
ENTRYPOINT ["dotnet", "LackBot.API.dll"]
