version: '3.7'
services:
    mongo:
        image: mongo
        ports:
            - '27017:27017'
        networks:
            - db
        volumes:
            - mongo_data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        restart: unless-stopped
    mongo-express:
        image: mongo-express
        ports:
            - '8081:8081'
        networks:
            - db
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
        restart: unless-stopped
networks:
    db:
        name: db
        driver: bridge
volumes:
    mongo_data:
        name: mongo_data
